server {
    listen 80;
    charset utf-8;

    location / {
        proxy_pass http://frontend;
    }

    location /api/random {
        proxy_pass http://color-api:5000/random;
        proxy_set_header Host $host;
    }

    location /api/stats/record {
        proxy_pass http://stats-api:5001/record;
        proxy_set_header Host $host;
    }

    location /api/stats {
        proxy_pass http://stats-api:5001/stats;
        proxy_set_header Host $host;
    }

    location /api/health {
        proxy_pass http://health-api:5002/health;
        proxy_set_header Host $host;
    }
}